### PR TITLE
Promises reject error objects instead of strings.

### PR DESCRIPTION
**Pull request by wesdean**
These are the same changes I requested for shipitjs.local.

### CODE REVIEW

**Comment by gregberge** [comment]
@wesdean add a test please, I am rewriting all the project and without test I am not sure to backport it.

**Comment by wesdean** [comment]
Sure, how can I make a call to connection.run fail from a test?

Wes Dean
bro.wes.dean@gmail.com

**Comment by gregberge** [comment]
@wesdean I think it's better to do it on branch https://github.com/shipitjs/ssh-pool/tree/v2.0.0. You have Jest so you can modify https://github.com/shipitjs/ssh-pool/blob/v2.0.0/__mocks__/child_process.js and add a behaviour to return an error. Is it enough clear for you?

**Comment by wesdean** [comment]
Closing this request and applying changes to different branch as suggested.

**Pull request closed without merging**
