### PR TITLE
Added proxy support for deploying to hosts in a VPC

### PR DESCRIPTION
**Pull request by goz**
Related to the first mentioned issue on this thread https://github.com/shipitjs/shipit/issues/17

Commented one test case on logging, need to figure it out what goes wrong.

### CODE REVIEW

**Comment by timkelty** [comment]
This looks good to me. @neoziro any objection to me merging in?

**Comment by timkelty** [comment]
@gozali You've been in here more recently than I...can you share the rationale for `proxy` being its own arg for `ConnectionPool`, rather than passing `options.proxy`?

**Comment by goz** [comment]
@timkelty i'm thinking one-to-many relationships, one proxy server for many app server, that's why i moved this into it's own argument.

**Comment by gregberge** [comment]
@timkelty if it's good for you, you can merge it

**Comment by timkelty** [comment]
@gozali we need to either release this as 2.0, or make it non-breaking by passing `proxy` in the `options` object.

**Pull request merged**
