### PR TITLE
Allow passing of rsync options in connection.copy

### PR DESCRIPTION
**Pull request by timkelty**
Specifically, I'd like this so I can pass `--info=progress2` or `--progress` to `shipit.copy`

### CODE REVIEW

**Comment by trungfinity** [comment]
+1. It would be nice to be merged.

**Comment by gregberge** [comment]
@timkelty can you just put the commit b55768d without the release ? I would merge it next.

**Comment by timkelty** [comment]
@neoziro Yeah, I think that happened inadvertently.

**Comment by timkelty** [comment]
OK, it just has that 1 commit now.

**Pull request merged**
